import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Blob For Enginnner Article",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        {/*for the for all pages header we need here. */}
        <header>BlobArticle</header>
        {children}
        <footer>BlobArticle inc.All right Reserved</footer>
      </body>
    </html>
  );
}
